title: TileFusion
description: TileFusion is a highly efficient C++ macro kernel template library designed to elevate the level of abstraction in CUDA C for processing tiles.
baseurl: "/tilefusion-docs"
url: "https://tiledtensor.github.io/tilefusion-docs/"
authors:
  - name: "Ying Cao"
    email: "lcy.seso@gmail.com"
    github: "lcy-seso"
  - name: "Chengxiang Qi"
    email: "KuangjuX@outlook.com"
    github: "KuangjuX"

mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-mml-chtml"
  tags:  "none" # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    block:
      line_numbers: false
      start_line: 1
theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/microsoft/TileFusion" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - docs/index.md
  - docs/installation.md
  - docs/design/index.md
  - docs/examples/index.md
  - docs/benchmarks/index.md
  - docs/about.md

aux_links:
  "TileFusion on GitHub":
    - "//github.com/microsoft/TileFusion"

# Rouge syntax highlighting
rouge:
  line_numbers: false
  span:
    line_numbers: false
  block:
    line_numbers: false
  css_class: 'highlight'

# Custom CSS
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

# Include custom CSS
head_scripts:
  - /assets/css/custom.css
