title: TileFusion
description: TileFusion is a highly efficient C++ macro kernel template library designed to elevate the level of abstraction in CUDA C for processing tiles.
baseurl: "/tilefusion-docs"
url: "https://tiledtensor.github.io/tilefusion-docs/"
authors:
  - name: "Ying Cao"
    email: "lcy.seso@gmail.com"
    github: "lcy-seso"
  - name: "Chengxiang Qi"
    email: "KuangjuX@outlook.com"
    github: "KuangjuX"

mathjax:
  enable: true # MathJax equations, e.g. true, false (default)
  combo: "tex-mml-chtml"
  tags:  "none" # "none", "ams" (default), "all"
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"

markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false
theme: minima

minima:
  date_format: "%b %-d, %Y"
  social_links:
    - { platform: github,  user_url: "https://github.com/microsoft/TileFusion" }

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-toc

header_pages:
  - docs/index.md
  - docs/installation.md
  - docs/design/index.md
  - docs/examples/index.md
  - docs/benchmarks/index.md
  - docs/about.md

aux_links:
  "TileFusion on GitHub":
    - "//github.com/microsoft/TileFusion"

# Custom CSS
sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass
    - assets/css

# TOC configuration
toc:
  min_level: 1
  max_level: 3
  no_toc_section_class: no_toc
  list_class: toc
  sublist_class: sub
  item_class: item
  item_prefix: ""
  anchor_class: anchor
  item_class_active: active

# Default layout for markdown files
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: "docs"
      type: "pages"
    values:
      layout: "mathjax"
